#!/usr/bin/env bash

switch_to() {
	if [[ -z $TMUX ]]; then
		tmux attach-session -t $1
	else
		tmux switch-client -t $1
	fi
}

hydrate() {
	if [ -f $HOME/.tmux-sessions/$1 ]; then
		tmux send-keys -t $1 "source $HOME/.tmux-sessions/$1" c-M
	fi
}

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/ ~/Developer ~/Work -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -ds $selected_name -c $selected -n nvim
	hydrate $selected_name
	switch_to $selected_name
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected -n nvim
	hydrate $selected_name
fi

switch_to $selected_name
